# Example Site settings



header_pages:
  - index.md
  - about.md
  - challenges.md

footer: 'bon_vivant()'



permalink: /:categories/:title/

collections_dir: collections
collections:
  challenges:
    output: true
    permalink: /:collection/:path